---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: webappcontainer
          image: goutammandloi16/test:testing-v1
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8082
